### ISSUE TITLE
Flow errors

### ISSUE THREAD

**Issue by cristiancedenogallego** [aksonov/react-native-experimental-navigation#12]
node_modules/react-native-experimental-navigation/NavigationScenesReducer.js:72
 72:   nextState: NavigationParentState,
                  ^^^^^^^^^^^^^^^^^^^^^ property `index`. Property not found in
 93:       scenes: NavigationScenesReducer([], this.props.navigationState),
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: node_modules/react-native/Libraries/NavigationExperimental/NavigationTransitioner.js:93

node_modules/react-native-experimental-navigation/NavigationScenesReducer.js:72
 72:   nextState: NavigationParentState,
                  ^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
117:       nextProps.navigationState,
           ^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: node_modules/react-native/Libraries/NavigationExperimental/NavigationTransitioner.js:117

node_modules/react-native-experimental-navigation/NavigationScenesReducer.js:72
 72:   nextState: NavigationParentState,
                  ^^^^^^^^^^^^^^^^^^^^^ property `index`. Property not found in
117:       nextProps.navigationState,
           ^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: node_modules/react-native/Libraries/NavigationExperimental/NavigationTransitioner.js:117

node_modules/react-native-experimental-navigation/NavigationScenesReducer.js:73
 73:   prevState: ?NavigationParentState,
                   ^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in
118:       this.props.navigationState
           ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: node_modules/react-native/Libraries/NavigationExperimental/NavigationTransitioner.js:118

node_modules/react-native-experimental-navigation/NavigationScenesReducer.js:73
 73:   prevState: ?NavigationParentState,
                   ^^^^^^^^^^^^^^^^^^^^^ property `index`. Property not found in
118:       this.props.navigationState
           ^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: node_modules/react-native/Libraries/NavigationExperimental/NavigationTransitioner.js:118

node_modules/react-native-experimental-navigation/NavigationStateUtils.js:136
136:   const index = parentState.children.indexOf(parentState.children.find(child => child.key === key));
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ undefined. This type is incompatible with the expected param type of
 31:   children: Array<NavigationState>,
                       ^^^^^^^^^^^^^^^ object type. See: node_modules/react-native-experimental-navigation/NavigationTypeDefinition.js:31

node_modules/react-native-experimental-navigation/NavigationStateUtils.js:153
153:   const index = parentState.children.indexOf(parentState.children.find(child => child.key === key));
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ undefined. This type is incompatible with the expected param type of
 31:   children: Array<NavigationState>,
                       ^^^^^^^^^^^^^^^ object type. See: node_modules/react-native-experimental-navigation/NavigationTypeDefinition.js:31

node_modules/react-native-experimental-navigation/NavigationTypeDefinition.js:101
101: ) => ReactElement;
          ^^^^^^^^^^^^ ReactElement. Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)

node_modules/react-native-experimental-navigation/NavigationTypeDefinition.js:110
110: ) => ?ReactElement;
           ^^^^^^^^^^^^ ReactElement. Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)

**Comment by franleplant** [comment]
I have the same problem. It looks like flow defs are outdated. I might be able to help, but we should discuss about it.

**Comment by franleplant** [comment]
For future reference, you can ignore `.*/node_modules/react-native-navigation-experimental/.*` in your `.flowconfig` and ignore those errors.

Edit

The correct ignore path is

```
.*/node_modules/react-native-experimental-navigation/.*
```

Thanks @helielson

**Comment by helielson** [comment]
I'm also experiment the same erros.
@aksonov, any updates here?

**Comment by helielson** [comment]
@franleplant just a misunderstanding: the correct ignore path is `.*/node_modules/react-native-experimental-navigation/.*`.

**Comment by apolishch** [comment]
are there any plans to fix these errors?
