### ISSUE TITLE
License for this module

### ISSUE THREAD

**Issue by ciceroneves** [aksonov/react-native-experimental-navigation#14]
Hi guys,

What would be the license for this module? I tried to find it but without success.
I am importing react-native-router-flux into my private repo and I am required to provide the license for every package being imported.

Thanks in advance.

**Comment by kesha-antonov** [comment]
https://github.com/aksonov/react-native-experimental-navigation/pull/18
https://github.com/aksonov/react-native-experimental-navigation/pull/17

**Comment by ciceroneves** [comment]
Thanks!
