### ISSUE TITLE
remove react-addons-pure-render-mixin from dependencies

### ISSUE THREAD

**Issue by iamawebgeek** [aksonov/react-native-experimental-navigation#20]
After a fresh update of React and React Native I am getting an error of react-addons-pure-render-mixin package trying to resolve non-existing file. Current library is dependency on react-native-router-flux, where react-addons-pure-render-mixin existed before too, but on the latest version it's gone I guess after PR https://github.com/aksonov/react-native-router-flux/pull/1790/commits/e95532b85ce517c2663a0c2fceed055275368dc8, though still exists in this package on dependencies, causing fatal error on the app.

**Comment by aksonov** [comment]
Feel free to submit PR.

**Comment by iamawebgeek** [comment]
Created a PR here https://github.com/aksonov/react-native-experimental-navigation/pull/21
This is the first time I am doing any PR, so please, check carefully

**Comment by aksonov** [comment]
Thanks!
